### ISSUE TITLE
CI fails with  Not found: type StackWalker

### ISSUE THREAD

**Issue by phelps-sg** [cequence-io/openai-scala-client#35]
~~~
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/home/runner/work/openai-scala-client/openai-scala-client/"), "guice"):
[error]    io.cequence:openai-scala-core _2.12, _3
[error]    io.cequence:openai-scala-client _2.12, _3
[error] -- [E006] Not Found Error: /home/runner/work/openai-scala-client/openai-scala-client/openai-core/src/main/scala/io/cequence/openaiscala/StackWalkerUtil.java:8:17 
[error] 8 |  private static StackWalker walker = StackWalker.getInstance(StackWalker.Option.RETAIN_CLASS_REFERENCE);
[error]   |                 ^^^^^^^^^^^
[error]   |                 Not found: type StackWalker
[error]   |
[error]   | longer explanation available when compiling with `-explain`
[warn] one warning found
[error] one error found
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: io.cequence:openai-scala-core, io.cequence:openai-scala-client
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.librarymanagement.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:39)
[error] 	at sbt.librarymanagement.ConflictWarning$.apply(ConflictWarning.scala:19)
[error] 	at sbt.Classpaths$.$anonfun$ivyBaseSettings$71(Defaults.scala:3270)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] (core / Compile / compileIncremental) Compilation failed
[error] (guice / update) Conflicting cross-version suffixes in: io.cequence:openai-scala-core, io.cequence:openai-scala-client
[error] Total time: 9 s, completed Jun 18, 2023 11:54:58 AM
~~~

**Comment by peterbanda** [comment]
CI uses JDK 11 now
